#!/bin/sh
# Args: doi/isbn/arxiv/title [optional description]

# This is done in case of a description
if [[ "$#" -eq 2 ]]; then

    description=" - ${2}"
else
    description=""
fi

todo_path="/home/lizzy/Documents/theory/wiki/todo.md"
note_path="/home/lizzy/Documents/theory/notes"


# # Step 1: Figure out whether input DOI, ISBN, title, arxiv
#
## Step 2: Obtain bibtex citation + format

option="${1}"
case ${option} in
    stdin) echo "Doing stdin"
        tabbed="$(</dev/stdin)"
        ;;
    *) tabbed="$(pull_bib_entry.sh $option)"
        # Pulls bibtex from not stdin
        ;;
esac


if [[ "$tabbed" == *"@misc"* ]] && [[ "$tabbed" == *"arXiv"* ]]; then
    tabbed="$(echo "$tabbed" | sed 's/@misc/@article/' | sed 's/^}$/    journal = {arXiv preprint},\n    doi = {/')"$number"},
}"
fi

automations=true
if [[ ${2} == "skip_todo" || "$tabbed" == "@online{,"* ]]; then
    automations=false
fi

if $automations; then
    lastname="$(echo "$tabbed" | grep -e '^ *author' | sed 's/author *= *{*\([^,]*\)[},\.].*/\1/' | tr '[:upper:]' '[:lower:]' | awk '{$1=$1};1')"
    if [[ "$string" == *","* ]]; then
        lastname="$(echo "$tabbed" | grep -e '^ *author' | sed 's/author *= *{*\([^,]*\)[},\.].*/\1/' | tr '[:upper:]' '[:lower:]' | awk '{print $2}')"
    else
        lastname="$(echo "$tabbed" | grep -e '^ *author' | sed 's/author *= *{*\([^,]*\)[},\.].*/\1/' | tr '[:upper:]' '[:lower:]' | awk '{$1=$1};1')"
    fi
    lastname_length=${#lastname}
    lastname_no_spaces=$(echo "$lastname" | tr -d ' ')  # Remove all spaces
    lastname_no_spaces_length=${#lastname_no_spaces}
    if [[ $lastname == *","*" and "* ]]; then
        lastname="$(echo "$lastname" | sed 's/^[a-z]* ([a-z]*) and .*/\1/' )"
    # Just one space
    elif [[ $lastname == *" and "* ]]; then
        lastname="$(echo "$lastname" | awk '{print $2}')"
elif [[ $(( lastname_length - lastname_no_spaces_length )) -eq 1 ]]; then
        lastname="$(echo "$lastname" | awk '{print $2}')"
    fi
    # Crimethinc exception
    echo "Last name: '$lastname'"
    if [[ "$lastname" == "crimethinc. ex-workers collective}}" ]]; then
        lastname=crimethinc
    fi
    echo "Last name: '$lastname'"
    year="$(echo "$tabbed" | grep -e '^ *year' | sed 's/year *= *{\([0-9]*\).*/\1/')"
    echo "Year: $year"
    title="$(echo "$tabbed" | grep -e '^ *title' | sed 's/title *= *{\(.*\)},$/\1/' | sed 's/[:“”]//g' | tr '[:upper:]' '[:lower:]' )"

    echo "Title: $title"

    stopwordlist='a an are as be by do does from for has have how of in is it on really should sure the to was what who why with you'
    list=( $title )
    for word in "${list[@]}"; do
        if [[ ! " $stopwordlist " =~ .*\ $word\ .* ]]; then
            break
        fi
    done

    key="$(echo $lastname$year$word | tr -cd '[:alnum:]')"
    echo $key

    tabbed="$(echo "$tabbed" | sed 's/@\([a-zA-Z]*\){.*/@\1{'"$key"',/')"
    # echo "$tabbed"
fi


# Step 3: ensure everything is correct through nvim

# A couple enters to ensure whitespacing
final_entry=$(echo "$tabbed"$'\n'$'\n' | vipe --suffix bib)

if [ -z "${final_entry}" ]; then
    echo "Empty string"
    exit 1
fi

final_key="$(echo "$final_entry" | grep '^@.*' | sed 's/@[a-zA-Z]*{\(.*\),/\1/' )"

echo "$final_key"
# Step 4: add to bibliography
add_to_bib.sh "$final_entry"

# Step 5: add to todo or elsewhere

if [ ${2} != "skip_todo" ]; then
    echo "[[notes/$final_key|$final_key]]$description" >> "$todo_path"

    # Copies to clipboard
    echo "$final_key" | xargs | xclip -selection clipboard
    nvim "$note_path/$final_key.md"
fi
