#!/bin/sh
cd ~/Documents/theory/essays/presentations/
next_friday="$(date -d "next Friday" +"%Y-%m-%d")"
if [ "$(date +"%A")" == "Friday" ]; then
    # echo "Today is Friday"
    next_friday="$(date +"%Y-%m-%d")"
fi
filename="$next_friday.tex"
if [ ! -f "$filename" ]; then
    echo "Creating new presentation"
    cp template.tex $filename
    sed -i "s/Date/$next_friday/" $filename
fi
nvim $filename
