#!/bin/sh

bib_file="$HOME/Documents/theory/sources.bib"
choice=$(ls ~/Documents/theory/notes ~/Documents/theory/readings | sed -E 's/\..+$//' | sort -u | bemenu -nb '#445349' -sf '#445349' -sb '#F0C674' -nf '#F0C674')
if [[ "$choice" == "" ]]; then
    nvim ~/Documents/theory/notes
    exit 1
else
    # Remove relevant bib entry
    # First, find the boundaries
    start_line="$(grep -n "@.*{$choice," $bib_file | cut -d: -f1)"
    end_line="$(awk -v start=$start_line "NR >= start && /^}$/ {print NR + 1; exit}" $bib_file)"

    # Next extract the text
    extracted_text=$(awk -v s="$start_line" -v e="$end_line" 'NR >= s && NR <= e' $bib_file)
    sed -i "${start_line},${end_line}d" $bib_file
fi

# Either obtains new entry or updates name depending on if a period exists
if [[ "$1" == *.* ]]; then
    new_text="$(pull_bib_entry.sh "$1" | vipe --suffix bib )"
    new_name="$(echo "$new_text" | grep '^@.*' | sed 's/@[a-zA-Z]*{\(.*\),/\1/' )"
    echo "$new_name" | xargs | xclip -selection clipboard
else
    new_name=$1
    new_text="$(echo "$extracted_text" | sed "s/$choice/$new_name/" )"
fi


pdf=$(ls -d ~/Documents/theory/readings/* | grep $choice)
# $(zathura $pdf </dev/null >/dev/null 2>&1 & disown -h)
mda=$(echo $choice.md)
md=~/Documents/theory/notes/$mda

mv $pdf ~/Documents/theory/readings/$new_name.pdf
mv $md  ~/Documents/theory/notes/$new_name.md

grep -RiIlZ "$choice" ~/Documents/theory/* | xargs -0 sed -i "s/$choice/$new_name/g"

# echo "$new_text"

# Next, re-add the bib
add_to_bib.sh "$new_text"
