#!/bin/sh
cd ~/Documents/theory/
choice=$(ls ~/Documents/theory/readings | sed -E 's/\..+$//' | dmenu -nb '#445349' -sf '#445349' -sb '#F0C674' -nf '#F0C674')
if [[ "$choice" != "" ]]; then
    pdf=$(ls -d ~/Documents/theory/readings/* | grep $choice)
    $(zathura $pdf </dev/null >/dev/null 2>&1 & disown -h)
    mda=$(echo $choice.md)
    md=~/Documents/theory/notes/$mda
    #touch $md
    nvim $md
else
    nvim ~/Documents/theory/notes
fi
